"""
🛠️ JoJo AGI: Dynamic Skill Synthesizer
Enables continuous self-improvement by synthesizing, testing, and registering new Python tools:
- Takes code generated by the Agent Brain
- Runs optional tests in a separate process
- Persists valid skills to jojo_skills/
- Dynamically loads and makes them callable in runtime
"""

import os
import re
import sys
import time
import sqlite3
from typing import Tuple

WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SKILLS_DIR = os.path.join(WORKSPACE_ROOT, "jojo_skills")
DB_FILE = os.path.join(WORKSPACE_ROOT, "jojo_memory.db")

from jojo_agi.jojo_execution_engine import execute_python_code

def synthesize_and_save_skill(skill_name: str, python_code: str, test_code: str = "") -> str:
    """
    Synthesizes and registers a new Python skill for JoJo to use permanently.
    skill_name: unique python-friendly identifier (e.g., 'system_cleaner', 'youtube_downloader')
    python_code: complete python functions/classes implementing the skill
    test_code: optional python snippet to verify the skill works
    """
    clean_name = re.sub(r'[^a-zA-Z0-9_]', '_', skill_name.lower().strip())
    if not clean_name:
        return "⚠️ Invalid skill name."
    if not clean_name.startswith('jojo_'):
        clean_name = 'jojo_' + clean_name

    # Validate syntax first
    try:
        compile(python_code, f"<skill_{clean_name}>", "exec")
    except SyntaxError as e:
        return f"❌ Python Syntax Error in skill: {str(e)}"

    # If supplied, run the test in a separate process (not an OS sandbox).
    if test_code:
        full_test = f"{python_code}\n\n# --- Verification Test ---\n{test_code}"
        test_res = execute_python_code(full_test, timeout=15)
        if any(marker in test_res for marker in ("❌", "Traceback", "⏱", "⚠")):
            return f"❌ Skill verification failed during test run:\n{test_res}"

    # Write skill file
    skill_file = os.path.join(SKILLS_DIR, f"{clean_name}.py")
    try:
        os.makedirs(SKILLS_DIR, exist_ok=True)
        with open(skill_file, "w", encoding="utf-8") as f:
            f.write(f'"""\n⚡ Auto-synthesized JoJo Skill: {clean_name}\nCreated: {time.ctime()}\n"""\n\n')
            f.write(python_code)

        # Register in SQLite database
        try:
            conn = sqlite3.connect(DB_FILE)
            c = conn.cursor()
            c.execute('''
                INSERT INTO learned_skills (trigger_phrase, action_type, action_payload, created_at)
                VALUES (?, ?, ?, ?)
                ON CONFLICT(trigger_phrase) DO UPDATE SET action_payload=excluded.action_payload
            ''', (clean_name, "python_skill", skill_file, time.time()))
            conn.commit()
            conn.close()
        except Exception:
            pass

        verification = "Test passed." if test_code else "Syntax checked; no behavioral test was supplied."
        return f"Skill '{clean_name}' saved. {verification}"
    except Exception as e:
        return f"⚠️ Error writing skill file: {str(e)}"
